
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import os
from io import StringIO
import sys

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


# Get the absolute path to the current file
file_path = os.path.abspath(__file__)

# Get the directory containing the current file
output_path = os.path.dirname(file_path)

# Set the assets path to the "assets/frame0" directory inside the output path
assets_path = Path(output_path) / "Required files/assetsJI/frame0"


def relative_to_assets(path: str) -> Path:
    return assets_path / Path(path)


def JI(g1, g2, g3, e):
    sys.stdout = open("result.txt", "w")
    global x, y, z
    def f1(x, y, z): return eval(g1)
    def f2(x, y, z): return eval(g2)
    def f3(x, y, z): return eval(g3)

    # Initial setup
    x0 = 0
    y0 = 0
    z0 = 0
    count = 1

    # Reading tolerable error
    e = float(e)

    # Implementation of Jacobi Iteration
    print('\nCount\tx\ty\tz\n')

    condition = True

    while condition:
        x1 = f1(x0, y0, z0)
        y1 = f2(x0, y0, z0)
        z1 = f3(x0, y0, z0)
        print('%d\t%0.4f\t%0.4f\t%0.4f\n' % (count, x1, y1, z1))
        e1 = abs(x0-x1)
        e2 = abs(y0-y1)
        e3 = abs(z0-z1)

        count += 1
        x0 = x1
        y0 = y1
        z0 = z1

        condition = e1 > e and e2 > e and e3 > e
    sys.stdout.close()
    window.destroy()
    os.system('python result.py')


def test():
    f1 = (entry_1.get())
    f2 = entry_2.get()
    f3 = entry_3.get()
    e = entry_4.get()
    JI(f1, f2, f3, e)


def home():
    window.destroy()
    os.system('python mainframe.py')


window = Tk()

window.geometry("919x555+300+100")
window.configure(bg="#333131")


canvas = Canvas(
    window,
    bg="#333131",
    height=555,
    width=919,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
canvas.create_text(
    570.0,
    32.0,
    anchor="nw",
    text="Enter equation 1",
    fill="#FFFFFF",
    font=("Inter SemiBold", 24 * -1)
)

canvas.create_text(
    571.0,
    144.0,
    anchor="nw",
    text="Enter equation 2",
    fill="#FFFFFF",
    font=("Inter SemiBold", 24 * -1)
)

canvas.create_text(
    570.0,
    255.0,
    anchor="nw",
    text="Enter equation 3",
    fill="#FFFFFF",
    font=("Inter SemiBold", 24 * -1)
)

canvas.create_text(
    570.0,
    367.0,
    anchor="nw",
    text="Tolerable Error",
    fill="#FFFFFF",
    font=("Inter SemiBold", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=test,
    relief="flat"
)
button_1.place(
    x=583.0,
    y=479.0,
    width=175.0,
    height=47.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    671.0,
    91.5,
    image=entry_image_1
)

entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=550.0,
    y=70.0,
    width=242.0,
    height=41.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    671.0,
    203.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=550.0,
    y=182.0,
    width=242.0,
    height=40.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    671.0,
    315.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=550.0,
    y=294.0,
    width=242.0,
    height=41.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    671.0,
    424.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=550.0,
    y=404.0,
    width=242.0,
    height=39.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=home,
    relief="flat",
    bg="#333131"
)
button_2.place(
    x=865.0,
    y=12.0,
    width=43.0,
    height=34.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    227.0,
    277.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
